# @url_dev=http://localhost:3055/v1/api

# ### signup
# POST {{url_dev}}/shop/signup
# Content-Type: application/json
# x-api-key: abc12345678

# {
#     "name": "Hades Store",
#     "email": "hadesshop03@gmail.com",
#     "password": "hieudz1221"
# }


POST http://localhost:3055/v1/api/shop/signup
Content-Type: application/json
x-api-key: abc12345678

{
    "name": "Shop Name",
    "email": "shopname@gmail.com",
    "password": "hieudz1221"
}